defaults:
    partitions: 3
    replicationFactor: 1
    configurations:
        - retention.ms=1296000000 # 1.5 days
topics:
    - name: sb-all
    - name: cc-abn
    - name: cc-alex
    - name: cc-bgr
    - name: cc-boris
    - name: cc-boris
    - name: cc-ecod
    - name: cc-edoc
    - name: cc-eperiodica
    - name: cc-ethresearch
    - name: cc-hemu
    - name: cc-idsbb
    - name: cc-idslu
    - name: cc-idssg
    - name: cc-kbtg
    - name: cc-libib
    - name: cc-nb
    - name: cc-posters
    - name: cc-sbt
    - name: cc-serval
    - name: cc-sgbn
    - name: cc-vaud
    - name: cc-zora
    - name: cc-rero
    - name: cc-nebis
    - name: cc-phbern
    - name: memobase
    - name: hansource  
    - name: swisscollections-messages  
    - name: swisscollections-messages-out  
    - name: swisscollections-rawdata
    - name: swisscollections-filtered  
    - name: swisscollections-solrdoc  

